# Generated by Django 6.0.1 on 2026-01-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_add_file_type_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='is_favourite',
            field=models.BooleanField(default=False, help_text='Mark as favourite for quick access'),
        ),
    ]
