# Generated by Django 6.0.1 on 2026-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_telegramchannel_availability_checked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfig',
            name='download_files',
            field=models.BooleanField(default=False, help_text='Documents, audio, voice messages, stickers, etc.'),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='download_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channelconfig',
            name='download_videos',
            field=models.BooleanField(default=False),
        ),
    ]
