# Generated by Django 6.0.1 on 2026-01-13 13:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_historicalglobalsettings_historicaltelegramaccount'),
        ('audit', '0014_telegramchannel_telegram_counts_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalChannelConfig',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('auto_download_enabled', models.BooleanField(default=False, help_text='Automatically download new media from this source')),
                ('download_photos', models.BooleanField(default=False)),
                ('download_videos', models.BooleanField(default=False)),
                ('download_files', models.BooleanField(default=False, help_text='Documents, audio, voice messages, stickers, etc.')),
                ('file_type_priority', models.JSONField(blank=True, default=list, help_text='Order in which file types are downloaded (first = highest priority)')),
                ('priority', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='Higher priority sources are processed first (1-10)')),
                ('deduplication_mode', models.CharField(choices=[('none', 'No Deduplication'), ('sha256', 'SHA256 Hash (Link to Original)')], default='none', help_text='How to handle duplicate files', max_length=20)),
                ('archive_enabled', models.BooleanField(default=False, help_text='Archive text messages from this source')),
                ('download_thumbnails', models.BooleanField(default=True, help_text='Always download thumbnails for media posts (enables browsing without full downloads)')),
                ('thumbnail_size', models.CharField(choices=[('s', 'Small (~100px)'), ('m', 'Medium (~320px)'), ('x', 'Large (~800px)'), ('y', 'Extra Large (~1280px)')], default='m', help_text='Size of downloaded thumbnails (smaller = less storage, larger = better preview)', max_length=1)),
                ('is_paused', models.BooleanField(default=False, help_text='Pause all downloads from this source')),
                ('last_downloaded_message_id', models.BigIntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('downloaded_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Channel Config',
                'verbose_name_plural': 'historical Channel Configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTelegramChannel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_type', models.CharField(choices=[('channel', 'Channel'), ('supergroup', 'Supergroup'), ('group', 'Group'), ('private', 'Private Chat')], max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('member_count', models.IntegerField(default=0)),
                ('avatar', models.TextField(blank=True, max_length=100, null=True)),
                ('is_favourite', models.BooleanField(default=False, help_text='Mark as favourite for quick access')),
                ('joined_at', models.DateTimeField(blank=True, help_text='When the account joined this channel', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has Telegram verification badge')),
                ('is_scam', models.BooleanField(default=False, help_text='Flagged as scam by Telegram')),
                ('is_fake', models.BooleanField(default=False, help_text='Flagged as fake by Telegram')),
                ('is_restricted', models.BooleanField(default=False, help_text='Has content restrictions')),
                ('is_broadcast', models.BooleanField(default=False, help_text='True broadcast channel (not group)')),
                ('is_megagroup', models.BooleanField(default=False, help_text='Supergroup')),
                ('is_gigagroup', models.BooleanField(default=False, help_text='Broadcast group (large group)')),
                ('has_signatures', models.BooleanField(default=False, help_text='Shows author signatures on posts')),
                ('has_linked_chat', models.BooleanField(default=False, help_text='Has linked discussion group')),
                ('slowmode_seconds', models.IntegerField(default=0, help_text='Slowmode delay in seconds')),
                ('is_forum', models.BooleanField(default=False, help_text='Forum/topics enabled')),
                ('noforwards', models.BooleanField(default=False, help_text='Forwarding content is prohibited')),
                ('join_to_send', models.BooleanField(default=False, help_text='Must join to send messages')),
                ('join_request', models.BooleanField(default=False, help_text='Join requests required')),
                ('boost_level', models.IntegerField(blank=True, help_text='Channel boost level', null=True)),
                ('has_left', models.BooleanField(default=False, help_text='Account has left this channel')),
                ('availability_status', models.CharField(choices=[('active', 'Active'), ('unavailable', 'Unavailable'), ('deleted', 'Deleted'), ('restricted', 'Restricted'), ('private', 'Private'), ('unknown', 'Unknown')], default='active', help_text='Current availability status of the channel', max_length=20)),
                ('availability_checked_at', models.DateTimeField(blank=True, help_text='When availability was last checked', null=True)),
                ('availability_error', models.TextField(blank=True, help_text='Error message if channel is unavailable')),
                ('telegram_photo_count', models.IntegerField(default=0, help_text='Total photos in channel')),
                ('telegram_video_count', models.IntegerField(default=0, help_text='Total videos in channel')),
                ('telegram_file_count', models.IntegerField(default=0, help_text='Total files in channel (docs + voice + round + gif)')),
                ('telegram_counts_updated_at', models.DateTimeField(blank=True, help_text='When media counts were last fetched', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.telegramaccount')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Telegram Channel',
                'verbose_name_plural': 'historical Telegram Channels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
