# Generated by Django 6.0.1 on 2026-01-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_historicalchannelconfig_historicaltelegramchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio/about text'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='birthday',
            field=models.CharField(blank=True, help_text='Birthday if set', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='business_intro',
            field=models.TextField(blank=True, help_text='Business introduction text'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='business_location',
            field=models.CharField(blank=True, help_text='Business location', max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='business_work_hours',
            field=models.JSONField(blank=True, help_text='Business work hours', null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='common_chats_count',
            field=models.IntegerField(default=0, help_text='Number of common chats with scanning account'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='contact_require_premium',
            field=models.BooleanField(default=False, help_text='Requires premium to contact'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='full_profile_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When full profile was last fetched', null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='has_pinned_stories',
            field=models.BooleanField(default=False, help_text='Has pinned stories'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='has_scheduled_messages',
            field=models.BooleanField(default=False, help_text='Uses scheduled messages'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='User is blocking scanning account'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='personal_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Personal channel ID', null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='phone_calls_available',
            field=models.BooleanField(default=False, help_text='Can receive phone calls'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='pinned_message_id',
            field=models.BigIntegerField(blank=True, help_text='Pinned message ID in DM', null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='private_forward_name',
            field=models.CharField(blank=True, help_text='Name shown when forwarding is restricted', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='video_calls_available',
            field=models.BooleanField(default=False, help_text='Can receive video calls'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='voice_messages_forbidden',
            field=models.BooleanField(default=False, help_text='Blocks voice messages'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='bio',
            field=models.TextField(blank=True, help_text='User bio/about text'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='birthday',
            field=models.CharField(blank=True, help_text='Birthday if set', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='business_intro',
            field=models.TextField(blank=True, help_text='Business introduction text'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='business_location',
            field=models.CharField(blank=True, help_text='Business location', max_length=500),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='business_work_hours',
            field=models.JSONField(blank=True, help_text='Business work hours', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='common_chats_count',
            field=models.IntegerField(default=0, help_text='Number of common chats with scanning account'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='contact_require_premium',
            field=models.BooleanField(default=False, help_text='Requires premium to contact'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='full_profile_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When full profile was last fetched', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='has_pinned_stories',
            field=models.BooleanField(default=False, help_text='Has pinned stories'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='has_scheduled_messages',
            field=models.BooleanField(default=False, help_text='Uses scheduled messages'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='User is blocking scanning account'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='personal_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Personal channel ID', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='phone_calls_available',
            field=models.BooleanField(default=False, help_text='Can receive phone calls'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='pinned_message_id',
            field=models.BigIntegerField(blank=True, help_text='Pinned message ID in DM', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='private_forward_name',
            field=models.CharField(blank=True, help_text='Name shown when forwarding is restricted', max_length=255),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='video_calls_available',
            field=models.BooleanField(default=False, help_text='Can receive video calls'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='voice_messages_forbidden',
            field=models.BooleanField(default=False, help_text='Blocks voice messages'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('message_received', 'Message Received'), ('message_archived', 'Message Archived'), ('user_tracked', 'User Tracked'), ('photo_downloaded', 'Profile Photo Downloaded'), ('download_queued', 'Download Queued'), ('download_started', 'Download Started'), ('download_completed', 'Download Completed'), ('download_failed', 'Download Failed'), ('history_scan_started', 'History Scan Started'), ('history_scan_completed', 'History Scan Completed'), ('member_scan_started', 'Member Scan Started'), ('member_scan_progress', 'Member Scan Progress'), ('member_scan_completed', 'Member Scan Completed'), ('profile_fetch_started', 'Profile Fetch Started'), ('profile_fetched', 'Profile Fetched'), ('profile_fetch_completed', 'Profile Fetch Completed'), ('availability_check_started', 'Availability Check Started'), ('availability_check_completed', 'Availability Check Completed'), ('flood_wait', 'Flood Wait'), ('error', 'Error')], db_index=True, max_length=50),
        ),
    ]
