# Generated by Django 6.0.1 on 2026-01-14 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0016_historicaltelegramuser_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltelegramchannel',
            name='is_favourite',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use UserMonitoredSource for user-based pinning'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='is_favourite',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use UserMonitoredSource for user-based pinning'),
        ),
        migrations.CreateModel(
            name='UserMonitoredSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_by', to='audit.telegramchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitored Source',
                'verbose_name_plural': 'Monitored Sources',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
