# Generated by Django 6.0.1 on 2026-01-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_alter_historicaltelegramchannel_is_favourite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='bypass_listener',
            field=models.BooleanField(default=False, help_text='Skip real-time message tracking for this source'),
        ),
        migrations.AddField(
            model_name='historicalchannelconfig',
            name='bypass_listener',
            field=models.BooleanField(default=False, help_text='Skip real-time message tracking for this source'),
        ),
    ]
