# Generated by Django 6.0.1 on 2026-01-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_add_exclusion_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfig',
            name='download_thumbnails',
            field=models.BooleanField(default=False, help_text='Always download thumbnails for media posts (enables browsing without full downloads)'),
        ),
        migrations.AlterField(
            model_name='historicalchannelconfig',
            name='download_thumbnails',
            field=models.BooleanField(default=False, help_text='Always download thumbnails for media posts (enables browsing without full downloads)'),
        ),
    ]
