# Generated by Django 6.0.1 on 2026-01-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_globalsettings_event_processing_enabled_and_more'),
        ('audit', '0022_exclusionrule_exclusion_listener_lookup_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='seen_by_accounts',
            field=models.ManyToManyField(blank=True, help_text='Accounts that have received events from this channel', related_name='visible_channels', to='accounts.telegramaccount'),
        ),
    ]
