# Generated by Django 6.0.1 on 2026-01-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0032_messageentity_entity_url_gin_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusergroupmembership',
            name='active',
            field=models.BooleanField(default=True, help_text='False if user explicitly left/was kicked'),
        ),
        migrations.AddField(
            model_name='historicalusergroupmembership',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='When the user left the group', null=True),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='active',
            field=models.BooleanField(default=True, help_text='False if user explicitly left/was kicked'),
        ),
        migrations.AddField(
            model_name='usergroupmembership',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='When the user left the group', null=True),
        ),
    ]
