# Generated by Django 6.0.1 on 2026-02-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0033_historicalusergroupmembership_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessageentity',
            name='entity_type',
            field=models.CharField(choices=[('url', 'URL'), ('text_url', 'Text URL'), ('domain', 'Domain'), ('mention', '@Mention'), ('mention_name', 'User Mention'), ('hashtag', 'Hashtag'), ('cashtag', 'Cashtag'), ('bot_command', 'Bot Command'), ('email', 'Email'), ('phone', 'Phone Number'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('strikethrough', 'Strikethrough'), ('code', 'Code'), ('pre', 'Pre-formatted'), ('spoiler', 'Spoiler'), ('blockquote', 'Blockquote'), ('custom_emoji', 'Custom Emoji')], max_length=20),
        ),
        migrations.AlterField(
            model_name='messageentity',
            name='entity_type',
            field=models.CharField(choices=[('url', 'URL'), ('text_url', 'Text URL'), ('domain', 'Domain'), ('mention', '@Mention'), ('mention_name', 'User Mention'), ('hashtag', 'Hashtag'), ('cashtag', 'Cashtag'), ('bot_command', 'Bot Command'), ('email', 'Email'), ('phone', 'Phone Number'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('strikethrough', 'Strikethrough'), ('code', 'Code'), ('pre', 'Pre-formatted'), ('spoiler', 'Spoiler'), ('blockquote', 'Blockquote'), ('custom_emoji', 'Custom Emoji')], max_length=20),
        ),
    ]
