# Generated by Django 6.0.2 on 2026-03-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0035_remove_historicaltelegramuser_last_seen_and_more'),
        ('downloads', '0026_alter_downloadtask_pending_reason_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forwardsource',
            index=models.Index(fields=['message'], name='audit_forwa_message_c05db0_idx'),
        ),
        migrations.AddIndex(
            model_name='messageentity',
            index=models.Index(fields=['message', 'entity_type'], name='audit_messa_message_14ae24_idx'),
        ),
    ]
