# Generated by Django 6.0.2 on 2026-03-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0040_telegram_link'),
        ('downloads', '0028_add_archived_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessageentity',
            name='channel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel'),
        ),
        migrations.AddField(
            model_name='messageentity',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_entities', to='audit.telegramchannel'),
        ),
        migrations.AddIndex(
            model_name='messageentity',
            index=models.Index(fields=['channel', 'entity_type'], name='audit_messa_channel_8e5e49_idx'),
        ),
    ]
