# Generated by Django 6.0.2 on 2026-03-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0043_add_composite_index_historicaltelegramchannel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usergroupmembership',
            index=models.Index(fields=['user', 'active'], name='ugm_user_active_idx'),
        ),
    ]
