# Generated by Django 6.0.2 on 2026-03-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0046_historicaltglink_tglink_historicaltglinkevent_and_more'),
        ('downloads', '0031_add_media_dimensions_and_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('message_processed', 'Message Processed'), ('user_tracked', 'User Tracked'), ('photo_downloaded', 'Profile Photo Downloaded'), ('download_queued', 'Download Queued'), ('download_started', 'Download Started'), ('download_completed', 'Download Completed'), ('download_failed', 'Download Failed'), ('history_scan_started', 'History Scan Started'), ('history_scan_completed', 'History Scan Completed'), ('history_scan_cancelled', 'History Scan Cancelled'), ('member_scan_started', 'Member Scan Started'), ('member_scan_completed', 'Member Scan Completed'), ('member_scan_cancelled', 'Member Scan Cancelled'), ('profile_fetch_started', 'Profile Fetch Started'), ('profile_fetched', 'Profile Fetched'), ('profile_fetch_completed', 'Profile Fetch Completed'), ('availability_check_started', 'Availability Check Started'), ('availability_check_completed', 'Availability Check Completed'), ('source_auto_archived', 'Source Auto-Archived'), ('channel_sync_started', 'Channel Sync Started'), ('channel_sync_completed', 'Channel Sync Completed'), ('channel_sync_cancelled', 'Channel Sync Cancelled'), ('refresh_stats_started', 'Refresh Stats Started'), ('refresh_stats_completed', 'Refresh Stats Completed'), ('media_counts_updated', 'Media Counts Updated'), ('user_media_delete_started', 'User Media Delete Started'), ('user_media_delete_completed', 'User Media Delete Completed'), ('tglink_resolved', 'Invite Link Resolved'), ('tglink_failed', 'Invite Link Resolution Failed'), ('reaction_scan_completed', 'Reaction Scan Completed'), ('flood_wait', 'Flood Wait'), ('error', 'Error')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='Telegram user ID of the reactor')),
                ('emoji', models.CharField(help_text='Unicode emoji or custom:ID for custom emoji', max_length=100)),
                ('is_custom_emoji', models.BooleanField(default=False)),
                ('custom_emoji_id', models.BigIntegerField(blank=True, null=True)),
                ('reacted_at', models.DateTimeField(blank=True, help_text='When the reaction was made (from Telegram if available)', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(help_text='Channel where the reaction occurred (denormalized for fast queries)', on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='audit.telegramchannel')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to='downloads.archivedmessage')),
                ('user', models.ForeignKey(blank=True, help_text='Linked TelegramUser if tracked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions', to='audit.telegramuser')),
            ],
            options={
                'verbose_name': 'User Reaction',
                'verbose_name_plural': 'User Reactions',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['telegram_user_id'], name='audit_userr_telegra_6650ca_idx'), models.Index(fields=['channel'], name='audit_userr_channel_0d67cb_idx'), models.Index(fields=['emoji'], name='audit_userr_emoji_50c1b6_idx'), models.Index(fields=['channel', 'telegram_user_id'], name='audit_userr_channel_ba2b56_idx'), models.Index(fields=['telegram_user_id', 'emoji'], name='audit_userr_telegra_623b76_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'telegram_user_id', 'emoji'), name='unique_user_reaction_per_message')],
            },
        ),
    ]
