# Generated by Django 6.0.1 on 2026-04-18 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0047_alter_activitylog_activity_type_userreaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramUserAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                (
                    "username",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("observation_count", models.PositiveIntegerField(default=1)),
                (
                    "first_seen_message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Telegram message_id where this alias was first observed",
                        null=True,
                    ),
                ),
                (
                    "first_seen_channel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Channel where this alias was first observed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="audit.telegramchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="audit.telegramuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram User Alias",
                "verbose_name_plural": "Telegram User Aliases",
                "ordering": ["-last_seen"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_seen"],
                        name="audit_teleg_user_id_8f5938_idx",
                    ),
                    models.Index(
                        fields=["username"], name="audit_teleg_usernam_a96da2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "first_name", "last_name", "username"),
                        name="unique_user_alias_triple",
                    )
                ],
            },
        ),
    ]
