# Generated by Django 6.0.1 on 2026-04-22 05:56

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0048_telegramuseralias"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("url", "URL"),
                            ("text_url", "Text URL"),
                            ("domain", "Domain"),
                            ("mention", "@Mention"),
                            ("mention_name", "User Mention"),
                            ("hashtag", "Hashtag"),
                            ("cashtag", "Cashtag"),
                            ("bot_command", "Bot Command"),
                            ("email", "Email"),
                            ("phone", "Phone Number"),
                            ("bold", "Bold"),
                            ("italic", "Italic"),
                            ("underline", "Underline"),
                            ("strikethrough", "Strikethrough"),
                            ("code", "Code"),
                            ("pre", "Pre-formatted"),
                            ("spoiler", "Spoiler"),
                            ("blockquote", "Blockquote"),
                            ("custom_emoji", "Custom Emoji"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("custom_emoji_id", models.BigIntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=50)),
                ("content_hash", models.CharField(max_length=32, unique=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Entity",
                "verbose_name_plural": "Global Entities",
                "indexes": [
                    models.Index(
                        fields=["entity_type"], name="audit_globa_entity__873f8c_idx"
                    ),
                    models.Index(
                        fields=["user_id"], name="audit_globa_user_id_5e6d43_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            models.F("url"), name="gin_trgm_ops"
                        ),
                        name="globalentity_url_trgm",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            models.F("text"), name="gin_trgm_ops"
                        ),
                        name="globalentity_text_trgm",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="historicalmessageentity",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="audit.globalentity",
            ),
        ),
        migrations.AddField(
            model_name="messageentity",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrences",
                to="audit.globalentity",
            ),
        ),
    ]
