# Generated by Django 6.0.1 on 2026-04-22 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0049_globalentity_historicalmessageentity_entity_and_more"),
        ("downloads", "0032_alter_taskrun_task_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="messageentity",
            name="audit_messa_entity__1fb23c_idx",
        ),
        migrations.RemoveIndex(
            model_name="messageentity",
            name="audit_messa_url_f6a226_idx",
        ),
        migrations.RemoveIndex(
            model_name="messageentity",
            name="audit_messa_user_id_a7879f_idx",
        ),
        migrations.RemoveIndex(
            model_name="messageentity",
            name="entity_url_gin_trgm",
        ),
        migrations.RemoveIndex(
            model_name="messageentity",
            name="entity_text_gin_trgm",
        ),
        migrations.RemoveIndex(
            model_name="messageentity",
            name="audit_messa_message_14ae24_idx",
        ),
        migrations.RemoveIndex(
            model_name="messageentity",
            name="audit_messa_channel_8e5e49_idx",
        ),
        migrations.RemoveField(
            model_name="historicalmessageentity",
            name="custom_emoji_id",
        ),
        migrations.RemoveField(
            model_name="historicalmessageentity",
            name="entity_type",
        ),
        migrations.RemoveField(
            model_name="historicalmessageentity",
            name="language",
        ),
        migrations.RemoveField(
            model_name="historicalmessageentity",
            name="text",
        ),
        migrations.RemoveField(
            model_name="historicalmessageentity",
            name="url",
        ),
        migrations.RemoveField(
            model_name="historicalmessageentity",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="messageentity",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="occurrences",
                to="audit.globalentity",
            ),
        ),
        migrations.AddIndex(
            model_name="messageentity",
            index=models.Index(
                fields=["message"], name="audit_messa_message_ee1440_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageentity",
            index=models.Index(
                fields=["channel"], name="audit_messa_channel_585f47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageentity",
            index=models.Index(
                fields=["entity"], name="audit_messa_entity__35e3b3_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="messageentity",
            name="custom_emoji_id",
        ),
        migrations.RemoveField(
            model_name="messageentity",
            name="entity_type",
        ),
        migrations.RemoveField(
            model_name="messageentity",
            name="language",
        ),
        migrations.RemoveField(
            model_name="messageentity",
            name="text",
        ),
        migrations.RemoveField(
            model_name="messageentity",
            name="url",
        ),
        migrations.RemoveField(
            model_name="messageentity",
            name="user_id",
        ),
    ]
