# Generated by Django 6.0.5 on 2026-05-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0052_alter_activitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltelegramuser',
            name='profile_photo_base64',
        ),
    ]
