# Generated by Django 6.0.5 on 2026-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0053_remove_historicaltelegramuser_profile_photo_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramchannel',
            name='joined_via_invite_hash',
            field=models.CharField(blank=True, default='', help_text='Invite hash extracted from the join URL (empty if joined by username)', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltelegramchannel',
            name='joined_via_url',
            field=models.URLField(blank=True, default='', help_text='Original URL the user submitted to Trawlr to join this channel', max_length=2000),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='joined_via_invite_hash',
            field=models.CharField(blank=True, default='', help_text='Invite hash extracted from the join URL (empty if joined by username)', max_length=255),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='joined_via_url',
            field=models.URLField(blank=True, default='', help_text='Original URL the user submitted to Trawlr to join this channel', max_length=2000),
        ),
    ]
