# Generated by Django 6.0.5 on 2026-06-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0054_historicaltelegramchannel_joined_via_invite_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='profile_photo_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
