# Generated by Django 6.0.5 on 2026-06-10 00:56

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0055_telegramuser_profile_photo_attempted_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='globalentity',
            name='globalentity_url_trgm',
        ),
        migrations.RemoveIndex(
            model_name='globalentity',
            name='globalentity_text_trgm',
        ),
        migrations.AddIndex(
            model_name='globalentity',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('url'), name='gin_trgm_ops'), name='globalentity_url_upper_trgm'),
        ),
        migrations.AddIndex(
            model_name='globalentity',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('text'), name='gin_trgm_ops'), name='globalentity_text_upper_trgm'),
        ),
        migrations.AddIndex(
            model_name='globalentity',
            index=models.Index(django.db.models.functions.text.Upper('text'), condition=models.Q(('entity_type__in', ['hashtag', 'mention', 'email', 'phone', 'domain'])), name='globalentity_text_upper'),
        ),
    ]
