# Generated by Django 6.0.1 on 2026-01-08 10:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_root', models.CharField(default='/data/trawlr', max_length=500)),
                ('filename_format', models.CharField(choices=[('guid', 'GUID.ext'), ('timestamp', 'timestamp_originalname.ext'), ('message_id', 'messageid_originalname.ext'), ('file_id', 'fileid.ext')], default='message_id', max_length=20)),
                ('default_retry_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('default_concurrent_downloads', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('api_id', models.CharField(max_length=20)),
                ('api_hash', models.CharField(max_length=64)),
                ('session_file', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('listener_status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('error', 'Error')], default='stopped', max_length=20)),
                ('listener_started_at', models.DateTimeField(blank=True, null=True)),
                ('listener_error', models.TextField(blank=True)),
                ('flood_wait_until', models.DateTimeField(blank=True, null=True)),
                ('max_concurrent_downloads', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Account',
                'verbose_name_plural': 'Telegram Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
