# Generated by Django 6.0.1 on 2026-01-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_session_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='display_name',
            field=models.CharField(blank=True, help_text='Friendly name for this account (defaults to phone number)', max_length=100),
        ),
    ]
