# Generated by Django 6.0.1 on 2026-01-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramaccount_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='listener_mode',
            field=models.CharField(choices=[('celery', 'Celery Worker'), ('service', 'Dedicated Service')], default='service', help_text='Which system manages this account listener', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='listener_status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('error', 'Error'), ('flood_wait', 'Flood Wait')], default='stopped', max_length=20),
        ),
    ]
