# Generated by Django 6.0.1 on 2026-01-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_globalsettings_filename_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='listener_mode',
            field=models.CharField(choices=[('service', 'Dedicated Service')], default='service', help_text='Which system manages this account listener', max_length=20),
        ),
    ]
