# Generated by Django 6.0.1 on 2026-01-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_telegramaccount_listener_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='download_profile_photos',
            field=models.BooleanField(default=True, help_text='Download profile photos when scanning members or tracking new users'),
        ),
    ]
