# Generated by Django 6.0.1 on 2026-01-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_telegramaccount_download_profile_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='download_queue_interval',
            field=models.IntegerField(choices=[(5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour')], default=10, help_text='How often to check for pending downloads'),
        ),
    ]
