# Generated by Django 6.0.1 on 2026-01-13 13:49

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_globalsettings_channel_stats_interval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGlobalSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('storage_root', models.CharField(default='/data/trawlr', max_length=500)),
                ('filename_format', models.CharField(choices=[('guid', 'GUID.jpg'), ('timestamp', 'timestamp_originalname.jpg'), ('message_id', 'messageid_originalname.jpg'), ('file_id', 'fileid.jpg')], default='guid', max_length=20)),
                ('default_retry_count', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('default_concurrent_downloads', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('download_queue_interval', models.IntegerField(choices=[(0, 'Disabled'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=10, help_text='How often to check for pending downloads')),
                ('channel_sync_interval', models.IntegerField(choices=[(0, 'Disabled'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=0, help_text='How often to sync channels for all accounts')),
                ('channel_stats_interval', models.IntegerField(choices=[(0, 'Disabled'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=0, help_text='How often to refresh channel statistics')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Global Settings',
                'verbose_name_plural': 'historical Global Settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTelegramAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('display_name', models.CharField(blank=True, help_text='Friendly name for this account (defaults to phone number)', max_length=100)),
                ('api_id', models.CharField(max_length=20)),
                ('api_hash', models.CharField(max_length=64)),
                ('session_file', models.CharField(blank=True, max_length=255)),
                ('session_string', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('listener_status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('error', 'Error'), ('flood_wait', 'Flood Wait')], default='stopped', max_length=20)),
                ('listener_mode', models.CharField(choices=[('service', 'Dedicated Service')], default='service', help_text='Which system manages this account listener', max_length=20)),
                ('listener_started_at', models.DateTimeField(blank=True, null=True)),
                ('listener_error', models.TextField(blank=True)),
                ('flood_wait_until', models.DateTimeField(blank=True, null=True)),
                ('max_concurrent_downloads', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('download_profile_photos', models.BooleanField(default=True, help_text='Download profile photos when scanning members or tracking new users')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Telegram Account',
                'verbose_name_plural': 'historical Telegram Accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
