# Generated by Django 6.0.1 on 2026-01-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_globalsettings_availability_check_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='store_raw_events',
            field=models.BooleanField(default=False, help_text='Store raw JSON event data before processing (for debugging/auditing)'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='store_raw_events',
            field=models.BooleanField(default=False, help_text='Store raw JSON event data before processing (for debugging/auditing)'),
        ),
    ]
