# Generated by Django 6.0.1 on 2026-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_globalsettings_forum_topics_sync_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='file_deduplication_enabled',
            field=models.BooleanField(default=True, help_text='Skip downloading files that already exist (matched by Telegram file_unique_id). Duplicate records will link to the original file instead of downloading again.'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='file_deduplication_enabled',
            field=models.BooleanField(default=True, help_text='Skip downloading files that already exist (matched by Telegram file_unique_id). Duplicate records will link to the original file instead of downloading again.'),
        ),
    ]
