# Generated by Django 6.0.1 on 2026-02-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_globalsettings_file_deduplication_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramaccount',
            name='pool_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='pool_clients',
            field=models.IntegerField(default=0),
        ),
    ]
