# Generated by Django 6.0.2 on 2026-03-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_globalsettings_azure_connection_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='auto_discover_onboard',
            field=models.BooleanField(default=False, help_text='Automatically run onboarding (fetch history & members) for auto-discovered sources'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='auto_discover_sources',
            field=models.BooleanField(default=False, help_text='Automatically create sources when the listener receives events from unknown channels/groups'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='auto_discover_onboard',
            field=models.BooleanField(default=False, help_text='Automatically run onboarding (fetch history & members) for auto-discovered sources'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='auto_discover_sources',
            field=models.BooleanField(default=False, help_text='Automatically create sources when the listener receives events from unknown channels/groups'),
        ),
    ]
