# Generated by Django 6.0.2 on 2026-03-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_globalsettings_auto_discover_sources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='auto_discover_onboard',
        ),
        migrations.RemoveField(
            model_name='historicalglobalsettings',
            name='auto_discover_onboard',
        ),
    ]
