# Generated by Django 6.0.5 on 2026-06-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_auto_discover_onboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='profile_photo_queue_interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=60, help_text='How often to dispatch backfill profile-photo downloads for scanned members (0 = disabled). Runs at strictly lower priority than file downloads.'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='profile_photo_queue_interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=60, help_text='How often to dispatch backfill profile-photo downloads for scanned members (0 = disabled). Runs at strictly lower priority than file downloads.'),
        ),
    ]
