# Generated by Django 6.0.5 on 2026-05-24 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WatchlistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("every", "Every occurrence"),
                            ("new", "New occurrence (first time only)"),
                        ],
                        default="every",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("url", "URL"),
                            ("text_url", "Text URL"),
                            ("domain", "Domain"),
                            ("mention", "@Mention"),
                            ("mention_name", "User Mention"),
                            ("hashtag", "Hashtag"),
                            ("cashtag", "Cashtag"),
                            ("bot_command", "Bot Command"),
                            ("email", "Email"),
                            ("phone", "Phone Number"),
                            ("bold", "Bold"),
                            ("italic", "Italic"),
                            ("underline", "Underline"),
                            ("strikethrough", "Strikethrough"),
                            ("code", "Code"),
                            ("pre", "Pre-formatted"),
                            ("spoiler", "Spoiler"),
                            ("blockquote", "Blockquote"),
                            ("custom_emoji", "Custom Emoji"),
                        ],
                        help_text="Which kind of entity to watch (URL, hashtag, @mention, etc.).",
                        max_length=20,
                    ),
                ),
                (
                    "entity_value",
                    models.CharField(
                        help_text="The exact value to match against, lowercased. For URLs use the full URL; for hashtags/mentions include the leading # or @.",
                        max_length=2000,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook (HTTP POST)"),
                            ("rabbitmq", "RabbitMQ queue"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_config",
                    models.JSONField(
                        default=dict,
                        help_text='Webhook: {"url": "...", "secret": "...", "headers": {...}}. RabbitMQ: {"queue": "...", "exchange": "", "routing_key": "...", "declare": false}.',
                    ),
                ),
                (
                    "cooldown_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = fire on every occurrence. >0 suppresses additional matches within the window.",
                    ),
                ),
                ("trigger_count", models.PositiveBigIntegerField(default=0)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Watchlist Entry",
                "verbose_name_plural": "Watchlist Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "mode"],
                        name="notificatio_is_acti_780a3b_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_value"],
                        name="notificatio_entity__fe5529_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_payload",
                    models.JSONField(
                        help_text="Snapshot of the JSON body that will be POSTed / published."
                    ),
                ),
                (
                    "match_context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Operator-facing summary: mode, entity_type, entity_value, message_id, channel_id.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed (will retry)"),
                            ("exhausted", "Exhausted (no more retries)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.watchlistentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Delivery",
                "verbose_name_plural": "Notification Deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "last_attempt_at"],
                        name="notificatio_status_95d863_idx",
                    ),
                    models.Index(
                        fields=["entry", "-created_at"],
                        name="notificatio_entry_i_5a2308_idx",
                    ),
                ],
            },
        ),
    ]
