# Generated by Django 6.0.5 on 2026-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistentry',
            name='mode',
            field=models.CharField(choices=[('all', 'Every occurrence'), ('new', 'New occurrence (first time only)')], default='all', max_length=20),
        ),
    ]
