# Generated by Django 6.0.1 on 2026-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_telegramaccount_listener_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='filename_format',
            field=models.CharField(choices=[('guid', 'GUID.jpg'), ('timestamp', 'timestamp_originalname.jpg'), ('message_id', 'messageid_originalname.jpg'), ('file_id', 'fileid.jpg')], default='guid', max_length=20),
        ),
    ]
