# Generated by Django 6.0.1 on 2026-01-15 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_globalsettings_media_counts_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='event_processing_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for event processing. If disabled, events will queue but not process.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='event_processor_batch_size',
            field=models.IntegerField(default=50, help_text='Number of events to process per worker cycle', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='event_processor_retry_backoff_max',
            field=models.IntegerField(default=300, help_text='Maximum retry backoff in seconds', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='event_processor_retry_backoff_min',
            field=models.IntegerField(default=10, help_text='Minimum retry backoff in seconds', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='event_processor_retry_count',
            field=models.IntegerField(default=5, help_text='Max retries for failed event processing', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='event_processing_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for event processing. If disabled, events will queue but not process.'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='event_processor_batch_size',
            field=models.IntegerField(default=50, help_text='Number of events to process per worker cycle', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='event_processor_retry_backoff_max',
            field=models.IntegerField(default=300, help_text='Maximum retry backoff in seconds', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='event_processor_retry_backoff_min',
            field=models.IntegerField(default=10, help_text='Minimum retry backoff in seconds', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='event_processor_retry_count',
            field=models.IntegerField(default=5, help_text='Max retries for failed event processing', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='historicaltelegramaccount',
            name='process_events',
            field=models.BooleanField(default=True, help_text='If disabled, events from this account will be queued but not processed'),
        ),
        migrations.AddField(
            model_name='telegramaccount',
            name='process_events',
            field=models.BooleanField(default=True, help_text='If disabled, events from this account will be queued but not processed'),
        ),
    ]
