# Generated by Django 6.0.1 on 2026-01-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_globalsettings_event_processing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='stuck_task_recovery_interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=3600, help_text='How often to check for and recover stuck tasks (0 = disabled, runs on startup only)'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='stuck_task_recovery_interval',
            field=models.IntegerField(choices=[(0, 'Disabled'), (5, '5 seconds'), (10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (30, '30 seconds'), (45, '45 seconds'), (60, '1 minute'), (180, '3 minutes'), (300, '5 minutes'), (600, '10 minutes'), (900, '15 minutes'), (1800, '30 minutes'), (2700, '45 minutes'), (3600, '1 hour'), (21600, '6 hours'), (43200, '12 hours'), (86400, '24 hours')], default=3600, help_text='How often to check for and recover stuck tasks (0 = disabled, runs on startup only)'),
        ),
    ]
