# Generated by Django 6.0.1 on 2026-01-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_globalsettings_store_raw_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='default_concurrent_downloads',
        ),
        migrations.RemoveField(
            model_name='historicalglobalsettings',
            name='default_concurrent_downloads',
        ),
    ]
