# Generated by Django 6.0.1 on 2026-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_globalsettings_default_concurrent_downloads_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='stream_raw_events',
            field=models.BooleanField(default=False, help_text='Stream raw events to trawlr.events.raw RabbitMQ queue for external processing'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='stream_raw_events',
            field=models.BooleanField(default=False, help_text='Stream raw events to trawlr.events.raw RabbitMQ queue for external processing'),
        ),
    ]
