# Generated by Django 6.0.1 on 2026-01-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_globalsettings_stream_raw_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='run_onboarding_for_new_sources',
            field=models.BooleanField(default=False, help_text='Automatically run onboarding tasks (fetch history & members) for newly detected sources during channel sync'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='run_onboarding_for_new_sources',
            field=models.BooleanField(default=False, help_text='Automatically run onboarding tasks (fetch history & members) for newly detected sources during channel sync'),
        ),
    ]
