# Generated by Django 6.0.1 on 2026-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_add_member_sync_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="auto_archive_unavailable",
            field=models.BooleanField(
                default=False,
                help_text="Automatically archive sources that are detected as unavailable (restricted, deleted, private) during availability checks",
            ),
        ),
        migrations.AddField(
            model_name="historicalglobalsettings",
            name="auto_archive_unavailable",
            field=models.BooleanField(
                default=False,
                help_text="Automatically archive sources that are detected as unavailable (restricted, deleted, private) during availability checks",
            ),
        ),
    ]
