# Generated by Django 6.0.2 on 2026-03-12 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_globalsettings_auto_archive_unavailable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='dialog_cache_limit',
            field=models.IntegerField(default=500, help_text='Number of dialogs to fetch when populating the Telegram entity cache (used for availability checks). Increase if channels are incorrectly marked as deleted.', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='dialog_cache_limit',
            field=models.IntegerField(default=500, help_text='Number of dialogs to fetch when populating the Telegram entity cache (used for availability checks). Increase if channels are incorrectly marked as deleted.', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
