# Generated by Django 6.0.2 on 2026-03-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_dialog_cache_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='tglink_resolution',
            field=models.BooleanField(default=False, help_text='Automatically resolve t.me invite links found in messages to catalog destination metadata'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='tglink_resolution',
            field=models.BooleanField(default=False, help_text='Automatically resolve t.me invite links found in messages to catalog destination metadata'),
        ),
    ]
