# Generated by Django 6.0.2 on 2026-03-29 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_globalsettings_reaction_scan_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='azure_connection_string',
            field=models.TextField(blank=True, default='', help_text='Azure Blob Storage connection string'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='azure_container_name',
            field=models.CharField(blank=True, default='', help_text='Azure Blob container name', max_length=200),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='azure_sas_expiry',
            field=models.IntegerField(default=3600, help_text='SAS token expiry time in seconds (60-86400)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='s3_access_key_id',
            field=models.CharField(blank=True, default='', help_text='S3 access key ID', max_length=200),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='s3_bucket_name',
            field=models.CharField(blank=True, default='', help_text='S3 bucket name', max_length=200),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='s3_endpoint_url',
            field=models.CharField(blank=True, default='', help_text='S3 endpoint URL (e.g. https://s3.amazonaws.com, or your MinIO/Wasabi URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='s3_presigned_url_expiry',
            field=models.IntegerField(default=3600, help_text='Presigned URL expiry time in seconds (60-86400)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='s3_region',
            field=models.CharField(blank=True, default='', help_text='S3 region (e.g. us-east-1). Leave blank for non-AWS providers.', max_length=50),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='s3_secret_access_key',
            field=models.CharField(blank=True, default='', help_text='S3 secret access key', max_length=200),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='storage_provider',
            field=models.CharField(choices=[('local', 'Local Filesystem'), ('s3', 'S3-Compatible Storage'), ('azure', 'Azure Blob Storage')], default='local', help_text='Where to store downloaded media files', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='azure_connection_string',
            field=models.TextField(blank=True, default='', help_text='Azure Blob Storage connection string'),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='azure_container_name',
            field=models.CharField(blank=True, default='', help_text='Azure Blob container name', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='azure_sas_expiry',
            field=models.IntegerField(default=3600, help_text='SAS token expiry time in seconds (60-86400)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='s3_access_key_id',
            field=models.CharField(blank=True, default='', help_text='S3 access key ID', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='s3_bucket_name',
            field=models.CharField(blank=True, default='', help_text='S3 bucket name', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='s3_endpoint_url',
            field=models.CharField(blank=True, default='', help_text='S3 endpoint URL (e.g. https://s3.amazonaws.com, or your MinIO/Wasabi URL)', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='s3_presigned_url_expiry',
            field=models.IntegerField(default=3600, help_text='Presigned URL expiry time in seconds (60-86400)', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)]),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='s3_region',
            field=models.CharField(blank=True, default='', help_text='S3 region (e.g. us-east-1). Leave blank for non-AWS providers.', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='s3_secret_access_key',
            field=models.CharField(blank=True, default='', help_text='S3 secret access key', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalglobalsettings',
            name='storage_provider',
            field=models.CharField(choices=[('local', 'Local Filesystem'), ('s3', 'S3-Compatible Storage'), ('azure', 'Azure Blob Storage')], default='local', help_text='Where to store downloaded media files', max_length=10),
        ),
    ]
