# Generated by Django 6.0.1 on 2026-01-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(db_index=True, default=5)),
                ('progress', models.IntegerField(default=0)),
                ('downloaded_bytes', models.BigIntegerField(default=0)),
                ('download_speed', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tasks', to='audit.telegramchannel')),
            ],
            options={
                'verbose_name': 'Download Task',
                'verbose_name_plural': 'Download Tasks',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('telegram_date', models.DateTimeField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_files', to='audit.telegramchannel')),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='downloads.downloadedfile')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_file', to='downloads.downloadtask')),
            ],
            options={
                'verbose_name': 'Downloaded File',
                'verbose_name_plural': 'Downloaded Files',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True)),
                ('sender_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_username', models.CharField(blank=True, max_length=255)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('forwards', models.IntegerField(default=0)),
                ('reactions', models.JSONField(blank=True, default=dict)),
                ('telegram_date', models.DateTimeField()),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_messages', to='audit.telegramchannel')),
            ],
            options={
                'verbose_name': 'Archived Message',
                'verbose_name_plural': 'Archived Messages',
                'ordering': ['-telegram_date'],
                'unique_together': {('channel', 'message_id')},
            },
        ),
        migrations.AddIndex(
            model_name='downloadtask',
            index=models.Index(fields=['status', 'priority'], name='downloads_d_status_234c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadtask',
            index=models.Index(fields=['channel', 'message_id'], name='downloads_d_channel_a67178_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadedfile',
            index=models.Index(fields=['channel', 'file_type'], name='downloads_d_channel_89bcc4_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadedfile',
            index=models.Index(fields=['sha256_hash'], name='downloads_d_sha256__bb40c3_idx'),
        ),
    ]
