# Generated by Django 6.0.1 on 2026-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_add_pending_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadtask',
            name='pending_reason',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('channel_paused', 'Channel Paused'), ('account_flood_wait', 'Account Flood Wait'), ('rate_limited', 'Rate Limited'), ('no_slots', 'No Available Slots')], default='queued', help_text='Why this task is pending (if applicable)', max_length=30),
        ),
    ]
