# Generated by Django 6.0.1 on 2026-01-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0006_archivedmessage_media_unavailable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='grouped_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Groups media belonging to same album', null=True),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Message is pinned in channel'),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='is_post',
            field=models.BooleanField(default=False, help_text='Channel post (vs group message)'),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='is_silent',
            field=models.BooleanField(default=False, help_text='Silent/no notification message'),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='noforwards',
            field=models.BooleanField(default=False, help_text='Message cannot be forwarded'),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='post_author',
            field=models.CharField(blank=True, help_text='Author signature on channel posts', max_length=255),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='ttl_period',
            field=models.IntegerField(blank=True, help_text='Time-to-live in seconds (disappearing message)', null=True),
        ),
    ]
