# Generated by Django 6.0.1 on 2026-01-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0008_add_taskrun_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('scan_history', 'Scan History'), ('scan_members', 'Scan Members'), ('check_availability', 'Check Availability'), ('sync_channels', 'Sync Channels')], db_index=True, max_length=50),
        ),
    ]
