# Generated by Django 6.0.1 on 2026-01-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0009_alter_taskrun_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedfile',
            name='deleted_from_disk',
            field=models.BooleanField(default=False),
        ),
    ]
