# Generated by Django 6.0.1 on 2026-01-15 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0014_alter_taskrun_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('unavailable', 'Unavailable'), ('archived', 'Completed')], db_index=True, default='pending', max_length=20),
        ),
    ]
