# Generated by Django 6.0.1 on 2026-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0015_archivedmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Message was deleted from source'),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Message was deleted from source'),
        ),
    ]
