# Generated by Django 6.0.1 on 2026-01-19 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0018_alter_taskrun_task_type'),
        ('events', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='raw_event',
            field=models.ForeignKey(blank=True, help_text='Raw event data that created this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_messages', to='events.rawevents'),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='raw_event',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Raw event data that created this message', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.rawevents'),
        ),
    ]
