# Generated by Django 6.0.1 on 2026-01-20 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0026_historicalforumtopic_forumtopic'),
        ('downloads', '0019_archivedmessage_raw_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='is_topic_message',
            field=models.BooleanField(default=False, help_text='True if this is a post in a topic, False if direct reply to message'),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='reply_to_top_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Topic ID (root message ID) when in a forum topic', null=True),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Forum topic this message belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='audit.forumtopic'),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='is_topic_message',
            field=models.BooleanField(default=False, help_text='True if this is a post in a topic, False if direct reply to message'),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='reply_to_top_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Topic ID (root message ID) when in a forum topic', null=True),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='topic',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Forum topic this message belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.forumtopic'),
        ),
    ]
