# Generated by Django 6.0.1 on 2026-01-22 01:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0029_historicalusermonitoredsource'),
        ('downloads', '0020_archivedmessage_is_topic_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDownloadTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('unavailable', 'Unavailable'), ('archived', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('pending_reason', models.CharField(blank=True, choices=[('queued', 'Queued'), ('channel_paused', 'Channel Paused'), ('account_flood_wait', 'Account Flood Wait'), ('rate_limited', 'Rate Limited'), ('no_slots', 'No Available Slots')], default='queued', help_text='Why this task is pending (if applicable)', max_length=30)),
                ('priority', models.IntegerField(db_index=True, default=5)),
                ('progress', models.IntegerField(default=0)),
                ('downloaded_bytes', models.BigIntegerField(default=0)),
                ('download_speed', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Download Task',
                'verbose_name_plural': 'historical Download Tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
