# Generated by Django 6.0.1 on 2026-01-23 07:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0032_messageentity_entity_url_gin_trgm_and_more'),
        ('downloads', '0022_alter_taskrun_task_type'),
        ('events', '0001_initial'),
    ]

    operations = [
        # 1. Add the search_vector field
        migrations.AddField(
            model_name='archivedmessage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),

        # 2. Create trigger function to auto-populate search_vector on INSERT/UPDATE
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION update_archivedmessage_search_vector()
                RETURNS trigger AS $$
                BEGIN
                    NEW.search_vector := to_tsvector('english', COALESCE(NEW.text, ''));
                    RETURN NEW;
                END $$ LANGUAGE plpgsql;

                CREATE TRIGGER archivedmessage_search_vector_trigger
                    BEFORE INSERT OR UPDATE OF text ON downloads_archivedmessage
                    FOR EACH ROW EXECUTE FUNCTION update_archivedmessage_search_vector();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS archivedmessage_search_vector_trigger ON downloads_archivedmessage;
                DROP FUNCTION IF EXISTS update_archivedmessage_search_vector();
            """,
        ),

        # 3. Backfill existing records (before creating index for performance)
        migrations.RunSQL(
            sql="""
                UPDATE downloads_archivedmessage
                SET search_vector = to_tsvector('english', COALESCE(text, ''))
                WHERE search_vector IS NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 4. Create GIN index on search_vector (after backfill for faster index creation)
        migrations.AddIndex(
            model_name='archivedmessage',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='downloads_a_search__f1a447_gin'),
        ),
    ]
