# Generated by Django 6.0.1 on 2026-02-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0033_historicalusergroupmembership_active_and_more'),
        ('downloads', '0023_archivedmessage_search_vector_and_more'),
        ('events', '0002_alter_rawevents_event_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archivedmessage',
            index=models.Index(fields=['-telegram_date'], name='downloads_a_telegra_b1721e_idx'),
        ),
    ]
