# Generated by Django 6.0.2 on 2026-03-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0036_add_perf_indexes_entity_forward'),
        ('downloads', '0026_alter_downloadtask_pending_reason_and_more'),
        ('events', '0002_alter_rawevents_event_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archivedmessage',
            index=models.Index(fields=['channel', '-telegram_date'], name='downloads_a_channel_70fe6f_idx'),
        ),
    ]
