# Generated by Django 6.0.1 on 2026-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0031_add_media_dimensions_and_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskrun",
            name="task_id",
            field=models.CharField(
                help_text="App-level UUID to link to dramatiq task. NOT the dramatiq task id.",
                max_length=100,
                unique=True,
            ),
        ),
    ]
