# Generated by Django 6.0.1 on 2026-01-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_type', models.CharField(choices=[('channel', 'Channel'), ('supergroup', 'Supergroup'), ('group', 'Group'), ('private', 'Private Chat')], max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('member_count', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='channel_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='accounts.telegramaccount')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_download_enabled', models.BooleanField(default=False, help_text='Automatically download new media from this source')),
                ('download_photos', models.BooleanField(default=True)),
                ('download_videos', models.BooleanField(default=True)),
                ('download_files', models.BooleanField(default=True, help_text='Documents, audio, voice messages, stickers, etc.')),
                ('priority', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='Higher priority sources are processed first (1-10)')),
                ('deduplication_mode', models.CharField(choices=[('none', 'No Deduplication'), ('sha256', 'SHA256 Hash (Link to Original)')], default='none', help_text='How to handle duplicate files', max_length=20)),
                ('archive_enabled', models.BooleanField(default=False, help_text='Archive text messages from this source')),
                ('is_paused', models.BooleanField(default=False, help_text='Pause all downloads from this source')),
                ('last_downloaded_message_id', models.BigIntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('downloaded_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='audit.telegramchannel')),
            ],
            options={
                'verbose_name': 'Channel Config',
                'verbose_name_plural': 'Channel Configs',
            },
        ),
    ]
