# Generated by Django 6.0.1 on 2026-01-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_telegram_user_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='file_type_priority',
            field=models.JSONField(blank=True, default=list, help_text='Order in which file types are downloaded (first = highest priority)'),
        ),
    ]
