# Generated by Django 6.0.1 on 2026-01-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_channelconfig_download_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='thumbnail_size',
            field=models.CharField(choices=[('s', 'Small (~100px)'), ('m', 'Medium (~320px)'), ('x', 'Large (~800px)'), ('y', 'Extra Large (~1280px)')], default='m', help_text='Size of downloaded thumbnails (smaller = less storage, larger = better preview)', max_length=1),
        ),
    ]
