# Generated by Django 6.0.1 on 2026-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_add_thumbnail_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='joined_at',
            field=models.DateTimeField(blank=True, help_text='When the account joined this channel', null=True),
        ),
    ]
