# Generated by Django 6.0.1 on 2026-01-09 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramaccount_display_name'),
        ('audit', '0007_telegramchannel_joined_at'),
        ('downloads', '0005_alter_downloadtask_pending_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('channel', 'Channel'), ('user', 'User'), ('message', 'Message')], max_length=20)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('violence', 'Violence'), ('pornography', 'Adult Content'), ('child_abuse', 'Child Abuse'), ('copyright', 'Copyright Violation'), ('fake', 'Fake Account / Scam'), ('illegal_drugs', 'Illegal Drugs'), ('personal_details', 'Personal Data Exposure'), ('other', 'Other')], max_length=30)),
                ('message', models.TextField(blank=True, help_text='Additional details provided with report')),
                ('reported_telegram_id', models.BigIntegerField(help_text='Telegram ID of reported entity')),
                ('reported_message_id', models.IntegerField(blank=True, help_text='Message ID if reporting a message', null=True)),
                ('reported_name', models.CharField(blank=True, help_text='Name/title at time of report', max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to='accounts.telegramaccount')),
                ('archived_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='downloads.archivedmessage')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='audit.telegramchannel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='audit.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
