# Generated by Django 6.0.1 on 2026-01-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_telegramreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='flagged_notes',
            field=models.TextField(blank=True, help_text='Notes about why user was flagged'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='flagged_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('violence', 'Violence'), ('pornography', 'Adult Content'), ('child_abuse', 'Child Abuse'), ('copyright', 'Copyright Violation'), ('fake', 'Fake Account / Scam'), ('illegal_drugs', 'Illegal Drugs'), ('personal_details', 'Personal Data Exposure'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for review/reporting'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='profile_photo_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded profile photo (not stored as file for safety)'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='profile_photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='reported_to_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='flagged_notes',
            field=models.TextField(blank=True, help_text='Notes about why user was flagged'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='flagged_reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam'), ('violence', 'Violence'), ('pornography', 'Adult Content'), ('child_abuse', 'Child Abuse'), ('copyright', 'Copyright Violation'), ('fake', 'Fake Account / Scam'), ('illegal_drugs', 'Illegal Drugs'), ('personal_details', 'Personal Data Exposure'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Flagged for review/reporting'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='profile_photo_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded profile photo (not stored as file for safety)'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='profile_photo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='reported_to_telegram',
            field=models.BooleanField(default=False),
        ),
    ]
