# Generated by Django 6.0.1 on 2026-01-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_historicaltelegramuser_flagged_at_and_more'),
        ('downloads', '0007_expanded_data_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='access_hash',
            field=models.BigIntegerField(blank=True, help_text='Telegram access hash for API calls', null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='emoji_status',
            field=models.JSONField(blank=True, help_text='Custom emoji status', null=True),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='is_close_friend',
            field=models.BooleanField(default=False, help_text='In close friends list'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='is_contact',
            field=models.BooleanField(default=False, help_text='Is in account contacts'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='User has deleted their account'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='is_mutual_contact',
            field=models.BooleanField(default=False, help_text='Mutual contact status'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='is_support',
            field=models.BooleanField(default=False, help_text='Official Telegram support account'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='lang_code',
            field=models.CharField(blank=True, help_text='User language preference', max_length=10),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='stories_hidden',
            field=models.BooleanField(default=False, help_text='Stories hidden from account'),
        ),
        migrations.AddField(
            model_name='historicaltelegramuser',
            name='stories_unavailable',
            field=models.BooleanField(default=False, help_text='No stories available'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='boost_level',
            field=models.IntegerField(blank=True, help_text='Channel boost level', null=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='has_left',
            field=models.BooleanField(default=False, help_text='Account has left this channel'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='has_linked_chat',
            field=models.BooleanField(default=False, help_text='Has linked discussion group'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='has_signatures',
            field=models.BooleanField(default=False, help_text='Shows author signatures on posts'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='True broadcast channel (not group)'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_fake',
            field=models.BooleanField(default=False, help_text='Flagged as fake by Telegram'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_forum',
            field=models.BooleanField(default=False, help_text='Forum/topics enabled'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_gigagroup',
            field=models.BooleanField(default=False, help_text='Broadcast group (large group)'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_megagroup',
            field=models.BooleanField(default=False, help_text='Supergroup'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Has content restrictions'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_scam',
            field=models.BooleanField(default=False, help_text='Flagged as scam by Telegram'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has Telegram verification badge'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='join_request',
            field=models.BooleanField(default=False, help_text='Join requests required'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='join_to_send',
            field=models.BooleanField(default=False, help_text='Must join to send messages'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='noforwards',
            field=models.BooleanField(default=False, help_text='Forwarding content is prohibited'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='slowmode_seconds',
            field=models.IntegerField(default=0, help_text='Slowmode delay in seconds'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='access_hash',
            field=models.BigIntegerField(blank=True, help_text='Telegram access hash for API calls', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='emoji_status',
            field=models.JSONField(blank=True, help_text='Custom emoji status', null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_close_friend',
            field=models.BooleanField(default=False, help_text='In close friends list'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_contact',
            field=models.BooleanField(default=False, help_text='Is in account contacts'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='User has deleted their account'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_mutual_contact',
            field=models.BooleanField(default=False, help_text='Mutual contact status'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_support',
            field=models.BooleanField(default=False, help_text='Official Telegram support account'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='lang_code',
            field=models.CharField(blank=True, help_text='User language preference', max_length=10),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='stories_hidden',
            field=models.BooleanField(default=False, help_text='Stories hidden from account'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='stories_unavailable',
            field=models.BooleanField(default=False, help_text='No stories available'),
        ),
        migrations.CreateModel(
            name='ForwardSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('channel', 'Channel'), ('user', 'User'), ('hidden', 'Hidden Sender')], max_length=20)),
                ('source_telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source_title', models.CharField(blank=True, help_text='Channel title or user name', max_length=255)),
                ('source_username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('original_message_id', models.BigIntegerField(blank=True, help_text='Original message ID in source', null=True)),
                ('original_date', models.DateTimeField(blank=True, help_text='Original post date', null=True)),
                ('original_author', models.CharField(blank=True, help_text='Post author signature', max_length=255)),
                ('from_name', models.CharField(blank=True, help_text='Name shown for hidden forward', max_length=255)),
                ('source_is_verified', models.BooleanField(default=False)),
                ('source_is_scam', models.BooleanField(default=False)),
                ('source_is_fake', models.BooleanField(default=False)),
                ('source_is_broadcast', models.BooleanField(default=False)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forward_source', to='downloads.archivedmessage')),
            ],
            options={
                'verbose_name': 'Forward Source',
                'verbose_name_plural': 'Forward Sources',
                'indexes': [models.Index(fields=['source_telegram_id'], name='audit_forwa_source__d9626e_idx'), models.Index(fields=['source_username'], name='audit_forwa_source__9bee00_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('url', 'URL'), ('text_url', 'Text URL'), ('mention', '@Mention'), ('mention_name', 'User Mention'), ('hashtag', 'Hashtag'), ('cashtag', 'Cashtag'), ('bot_command', 'Bot Command'), ('email', 'Email'), ('phone', 'Phone Number'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('strikethrough', 'Strikethrough'), ('code', 'Code'), ('pre', 'Pre-formatted'), ('spoiler', 'Spoiler'), ('blockquote', 'Blockquote'), ('custom_emoji', 'Custom Emoji')], max_length=20)),
                ('offset', models.IntegerField(help_text='Start position in text')),
                ('length', models.IntegerField(help_text='Length of entity')),
                ('text', models.TextField(blank=True, help_text='Extracted text content')),
                ('url', models.URLField(blank=True, help_text='URL for url/text_url types', max_length=2000)),
                ('user_id', models.BigIntegerField(blank=True, help_text='User ID for mention_name type', null=True)),
                ('custom_emoji_id', models.BigIntegerField(blank=True, help_text='Custom emoji document ID', null=True)),
                ('language', models.CharField(blank=True, help_text='Programming language for pre blocks', max_length=50)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='downloads.archivedmessage')),
            ],
            options={
                'verbose_name': 'Message Entity',
                'verbose_name_plural': 'Message Entities',
                'ordering': ['offset'],
                'indexes': [models.Index(fields=['entity_type'], name='audit_messa_entity__1fb23c_idx'), models.Index(fields=['url'], name='audit_messa_url_f6a226_idx'), models.Index(fields=['user_id'], name='audit_messa_user_id_a7879f_idx')],
            },
        ),
    ]
