# Generated by Django 6.0.1 on 2026-01-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_expanded_data_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='availability_checked_at',
            field=models.DateTimeField(blank=True, help_text='When availability was last checked', null=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='availability_error',
            field=models.TextField(blank=True, help_text='Error message if channel is unavailable'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='availability_status',
            field=models.CharField(choices=[('active', 'Active'), ('unavailable', 'Unavailable'), ('deleted', 'Deleted'), ('restricted', 'Restricted'), ('private', 'Private'), ('unknown', 'Unknown')], default='active', help_text='Current availability status of the channel', max_length=20),
        ),
    ]
