# Generated by Django 6.0.1 on 2026-01-10 12:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_alter_channelconfig_download_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('message_received', 'Message Received'), ('message_archived', 'Message Archived'), ('user_tracked', 'User Tracked'), ('photo_downloaded', 'Profile Photo Downloaded'), ('download_queued', 'Download Queued'), ('download_started', 'Download Started'), ('download_completed', 'Download Completed'), ('download_failed', 'Download Failed'), ('history_scan_started', 'History Scan Started'), ('history_scan_completed', 'History Scan Completed'), ('member_scan_started', 'Member Scan Started'), ('member_scan_progress', 'Member Scan Progress'), ('member_scan_completed', 'Member Scan Completed'), ('availability_check_started', 'Availability Check Started'), ('availability_check_completed', 'Availability Check Completed'), ('flood_wait', 'Flood Wait'), ('error', 'Error')], db_index=True, max_length=50)),
                ('source', models.CharField(choices=[('listener', 'Listener Service'), ('worker', 'Download Worker'), ('worker_telegram', 'Telegram Worker'), ('web', 'Web')], default='listener', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='audit.telegramchannel')),
                ('telegram_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='audit.telegramuser')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'activity_type'], name='audit_activ_timesta_ff7fef_idx'), models.Index(fields=['source', '-timestamp'], name='audit_activ_source_2f3951_idx')],
            },
        ),
    ]
