# Generated by Django 6.0.1 on 2026-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_add_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='telegram_counts_updated_at',
            field=models.DateTimeField(blank=True, help_text='When media counts were last fetched', null=True),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='telegram_file_count',
            field=models.IntegerField(default=0, help_text='Total files in channel (docs + voice + round + gif)'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='telegram_photo_count',
            field=models.IntegerField(default=0, help_text='Total photos in channel'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='telegram_video_count',
            field=models.IntegerField(default=0, help_text='Total videos in channel'),
        ),
    ]
