# Generated by Django 6.0.1 on 2026-01-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='If true, applies to all sources')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle exclusion on/off')),
                ('reason', models.TextField(blank=True, default='', help_text='Optional reason for exclusion')),
                ('trigger_count', models.PositiveIntegerField(default=0, help_text='Times this exclusion blocked a message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_rules', to='audit.telegramchannel')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_rules', to='audit.telegramuser')),
            ],
            options={
                'verbose_name': 'Exclusion Rule',
                'verbose_name_plural': 'Exclusion Rules',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('telegram_user',), name='unique_global_exclusion_per_user'), models.UniqueConstraint(condition=models.Q(('is_global', False)), fields=('telegram_user', 'source'), name='unique_source_exclusion_per_user')],
            },
        ),
    ]
