# Generated by Django 6.0.1 on 2026-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0021_alter_channelconfig_download_thumbnails_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exclusionrule',
            index=models.Index(fields=['telegram_user', 'is_active', 'is_global'], name='exclusion_listener_lookup_idx'),
        ),
    ]
