# Generated by Django 6.0.1 on 2026-01-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0023_telegramchannel_seen_by_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
