# Generated by Django 6.0.1 on 2026-01-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0024_alter_telegramchannel_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramchannel',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether Trawlr should process this source (disabled on leave)'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether Trawlr should process this source (disabled on leave)'),
        ),
    ]
