# Generated by Django 6.0.1 on 2026-01-20 00:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0025_historicaltelegramchannel_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalForumTopic',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('topic_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('icon_color', models.IntegerField(blank=True, help_text='Topic icon color ID', null=True)),
                ('icon_emoji_id', models.BigIntegerField(blank=True, help_text='Custom emoji ID for topic icon', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Topic is closed for new messages')),
                ('is_hidden', models.BooleanField(default=False, help_text='Topic is hidden from list')),
                ('is_pinned', models.BooleanField(default=False, help_text='Topic is pinned')),
                ('is_general', models.BooleanField(default=False, help_text='General topic (topic_id=1)')),
                ('message_count', models.IntegerField(default=0, help_text='Archived messages in this topic')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Forum Topic',
                'verbose_name_plural': 'historical Forum Topics',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.BigIntegerField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('icon_color', models.IntegerField(blank=True, help_text='Topic icon color ID', null=True)),
                ('icon_emoji_id', models.BigIntegerField(blank=True, help_text='Custom emoji ID for topic icon', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Topic is closed for new messages')),
                ('is_hidden', models.BooleanField(default=False, help_text='Topic is hidden from list')),
                ('is_pinned', models.BooleanField(default=False, help_text='Topic is pinned')),
                ('is_general', models.BooleanField(default=False, help_text='General topic (topic_id=1)')),
                ('message_count', models.IntegerField(default=0, help_text='Archived messages in this topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='audit.telegramchannel')),
            ],
            options={
                'verbose_name': 'Forum Topic',
                'verbose_name_plural': 'Forum Topics',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['channel', 'topic_id'], name='audit_forum_channel_2531af_idx')],
                'unique_together': {('channel', 'topic_id')},
            },
        ),
    ]
