# Generated by Django 6.0.1 on 2026-01-22 01:05

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_globalsettings_default_concurrent_downloads_and_more'),
        ('audit', '0029_historicalusermonitoredsource'),
        ('downloads', '0021_historicaldownloadtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExclusionRule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='If true, applies to all sources')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle exclusion on/off')),
                ('reason', models.TextField(blank=True, default='', help_text='Optional reason for exclusion')),
                ('trigger_count', models.PositiveIntegerField(default=0, help_text='Times this exclusion blocked a message')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('telegram_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramuser')),
            ],
            options={
                'verbose_name': 'historical Exclusion Rule',
                'verbose_name_plural': 'historical Exclusion Rules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalForwardSource',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('channel', 'Channel'), ('user', 'User'), ('hidden', 'Hidden Sender')], max_length=20)),
                ('source_telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source_title', models.CharField(blank=True, help_text='Channel title or user name', max_length=255)),
                ('source_username', models.CharField(blank=True, db_index=True, max_length=255)),
                ('original_message_id', models.BigIntegerField(blank=True, help_text='Original message ID in source', null=True)),
                ('original_date', models.DateTimeField(blank=True, help_text='Original post date', null=True)),
                ('original_author', models.CharField(blank=True, help_text='Post author signature', max_length=255)),
                ('from_name', models.CharField(blank=True, help_text='Name shown for hidden forward', max_length=255)),
                ('source_is_verified', models.BooleanField(default=False)),
                ('source_is_scam', models.BooleanField(default=False)),
                ('source_is_fake', models.BooleanField(default=False)),
                ('source_is_broadcast', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='downloads.archivedmessage')),
            ],
            options={
                'verbose_name': 'historical Forward Source',
                'verbose_name_plural': 'historical Forward Sources',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMessageEntity',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('url', 'URL'), ('text_url', 'Text URL'), ('mention', '@Mention'), ('mention_name', 'User Mention'), ('hashtag', 'Hashtag'), ('cashtag', 'Cashtag'), ('bot_command', 'Bot Command'), ('email', 'Email'), ('phone', 'Phone Number'), ('bold', 'Bold'), ('italic', 'Italic'), ('underline', 'Underline'), ('strikethrough', 'Strikethrough'), ('code', 'Code'), ('pre', 'Pre-formatted'), ('spoiler', 'Spoiler'), ('blockquote', 'Blockquote'), ('custom_emoji', 'Custom Emoji')], max_length=20)),
                ('offset', models.IntegerField(help_text='Start position in text')),
                ('length', models.IntegerField(help_text='Length of entity')),
                ('text', models.TextField(blank=True, help_text='Extracted text content')),
                ('url', models.URLField(blank=True, help_text='URL for url/text_url types', max_length=2000)),
                ('user_id', models.BigIntegerField(blank=True, help_text='User ID for mention_name type', null=True)),
                ('custom_emoji_id', models.BigIntegerField(blank=True, help_text='Custom emoji document ID', null=True)),
                ('language', models.CharField(blank=True, help_text='Programming language for pre blocks', max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='downloads.archivedmessage')),
            ],
            options={
                'verbose_name': 'historical Message Entity',
                'verbose_name_plural': 'historical Message Entities',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTelegramReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('channel', 'Channel'), ('user', 'User'), ('message', 'Message')], max_length=20)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('violence', 'Violence'), ('pornography', 'Adult Content'), ('child_abuse', 'Child Abuse'), ('copyright', 'Copyright Violation'), ('fake', 'Fake Account / Scam'), ('illegal_drugs', 'Illegal Drugs'), ('personal_details', 'Personal Data Exposure'), ('other', 'Other')], max_length=30)),
                ('message', models.TextField(blank=True, help_text='Additional details provided with report')),
                ('reported_telegram_id', models.BigIntegerField(help_text='Telegram ID of reported entity')),
                ('reported_message_id', models.IntegerField(blank=True, help_text='Message ID if reporting a message', null=True)),
                ('reported_name', models.CharField(blank=True, help_text='Name/title at time of report', max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.telegramaccount')),
                ('archived_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='downloads.archivedmessage')),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramuser')),
            ],
            options={
                'verbose_name': 'historical telegram report',
                'verbose_name_plural': 'historical telegram reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
