# Generated by Django 6.0.1 on 2026-01-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0030_historicalexclusionrule_historicalforwardsource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltelegramchannel',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='Whether onboarding tasks have been triggered for this channel'),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='onboarded',
            field=models.BooleanField(default=False, help_text='Whether onboarding tasks have been triggered for this channel'),
        ),
    ]
