# Generated by Django 6.0.1 on 2026-01-23 07:13

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0031_historicaltelegramchannel_onboarded_and_more'),
        ('downloads', '0022_alter_taskrun_task_type'),
    ]

    operations = [
        # Enable pg_trgm extension for trigram indexes
        TrigramExtension(),
        migrations.AddIndex(
            model_name='messageentity',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('url'), name='gin_trgm_ops'), name='entity_url_gin_trgm'),
        ),
        migrations.AddIndex(
            model_name='messageentity',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('text'), name='gin_trgm_ops'), name='entity_text_gin_trgm'),
        ),
    ]
