# Generated by Django 6.0.1 on 2026-02-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0034_alter_historicalmessageentity_entity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltelegramuser',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='historicaltelegramuser',
            name='message_count',
        ),
    ]
