# Generated by Django 6.0.1 on 2026-03-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0037_add_historical_id_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("red", "Red"),
                            ("yellow", "Yellow"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("pink", "Pink"),
                            ("teal", "Teal"),
                            ("grey", "Grey"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="historicaltelegramchannel",
            name="hist_tgchannel_id_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="historicaltelegramuser",
            name="hist_tguser_id_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="historicalusergroupmembership",
            name="hist_membership_id_date_idx",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="tags",
        ),
        migrations.AddField(
            model_name="telegramchannel",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="channels", to="audit.tag"
            ),
        ),
        migrations.RemoveField(
            model_name="historicaltelegramuser",
            name="tags",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="audit.tag"
            ),
        ),
    ]
