# Generated by Django 6.0.2 on 2026-03-07 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0039_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=500, unique=True)),
                ('identifier', models.CharField(help_text='Username or invite hash extracted from URL', max_length=255)),
                ('link_type', models.CharField(choices=[('channel', 'Channel'), ('user', 'User'), ('bot', 'Bot'), ('invite', 'Invite'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('invite_title', models.CharField(blank=True, max_length=255)),
                ('invite_member_count', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_links', to='audit.telegramchannel')),
                ('resolved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_links', to='audit.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
