# Generated by Django 6.0.2 on 2026-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0041_historicalmessageentity_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('message_processed', 'Message Processed'), ('user_tracked', 'User Tracked'), ('photo_downloaded', 'Profile Photo Downloaded'), ('download_queued', 'Download Queued'), ('download_started', 'Download Started'), ('download_completed', 'Download Completed'), ('download_failed', 'Download Failed'), ('history_scan_started', 'History Scan Started'), ('history_scan_completed', 'History Scan Completed'), ('history_scan_cancelled', 'History Scan Cancelled'), ('member_scan_started', 'Member Scan Started'), ('member_scan_completed', 'Member Scan Completed'), ('member_scan_cancelled', 'Member Scan Cancelled'), ('profile_fetch_started', 'Profile Fetch Started'), ('profile_fetched', 'Profile Fetched'), ('profile_fetch_completed', 'Profile Fetch Completed'), ('availability_check_started', 'Availability Check Started'), ('availability_check_completed', 'Availability Check Completed'), ('source_auto_archived', 'Source Auto-Archived'), ('channel_sync_started', 'Channel Sync Started'), ('channel_sync_completed', 'Channel Sync Completed'), ('channel_sync_cancelled', 'Channel Sync Cancelled'), ('refresh_stats_started', 'Refresh Stats Started'), ('refresh_stats_completed', 'Refresh Stats Completed'), ('media_counts_updated', 'Media Counts Updated'), ('user_media_delete_started', 'User Media Delete Started'), ('user_media_delete_completed', 'User Media Delete Completed'), ('flood_wait', 'Flood Wait'), ('error', 'Error')], db_index=True, max_length=50),
        ),
    ]
