# Generated by Django 6.0.2 on 2026-03-07 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_globalsettings_auto_archive_unavailable_and_more'),
        ('audit', '0042_alter_activitylog_activity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicaltelegramchannel',
            index=models.Index(fields=['id', '-history_date', '-history_id'], name='hist_tgch_id_date'),
        ),
    ]
