# Generated by Django 6.0.2 on 2026-03-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0044_add_user_active_index_usergroupmembership'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usergroupmembership',
            index=models.Index(fields=['active', 'last_seen'], name='ugm_active_lastseen_idx'),
        ),
        migrations.AddIndex(
            model_name='usergroupmembership',
            index=models.Index(condition=models.Q(('active', True)), fields=['user'], name='ugm_active_user_partial_idx'),
        ),
    ]
