# Generated by Django 6.0.2 on 2026-03-28 03:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_globalsettings_tglink_resolution_and_more'),
        ('audit', '0045_add_usergroupmembership_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTgLink',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, help_text='Resolved Telegram ID of the destination (null if preview-only)', null=True)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, help_text='Public username if available', max_length=255)),
                ('about', models.TextField(blank=True)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('is_megagroup', models.BooleanField(default=False)),
                ('is_broadcast', models.BooleanField(default=False)),
                ('is_request_needed', models.BooleanField(default=False, help_text='Join requests required')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_scam', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('flagged', models.BooleanField(db_index=True, default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(blank=True, editable=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, help_text='Linked TelegramChannel if this destination is a tracked source', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical TG Link',
                'verbose_name_plural': 'historical TG Links',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TgLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, help_text='Resolved Telegram ID of the destination (null if preview-only)', null=True)),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, help_text='Public username if available', max_length=255)),
                ('about', models.TextField(blank=True)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('is_megagroup', models.BooleanField(default=False)),
                ('is_broadcast', models.BooleanField(default=False)),
                ('is_request_needed', models.BooleanField(default=False, help_text='Join requests required')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_scam', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('flagged', models.BooleanField(db_index=True, default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Linked TelegramChannel if this destination is a tracked source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tg_links', to='audit.telegramchannel')),
            ],
            options={
                'verbose_name': 'TG Link',
                'verbose_name_plural': 'TG Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTgLinkEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invite_hash', models.CharField(db_index=True, help_text='Invite hash extracted from URL', max_length=255)),
                ('raw_url', models.URLField(help_text='Full URL as seen in the message', max_length=2000)),
                ('detected_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed'), ('expired', 'Expired'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('resolution_error', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, help_text='Channel where the invite link was posted (denormalized for fast queries)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('entity', models.ForeignKey(blank=True, db_constraint=False, help_text='The URL entity in the message where this invite link was found', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.messageentity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Account used to resolve the invite', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.telegramaccount')),
                ('source_link', models.ForeignKey(blank=True, db_constraint=False, help_text='Resolved destination (set once resolved)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.tglink')),
            ],
            options={
                'verbose_name': 'historical TG Link Event',
                'verbose_name_plural': 'historical TG Link Events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TgLinkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_hash', models.CharField(db_index=True, help_text='Invite hash extracted from URL', max_length=255)),
                ('raw_url', models.URLField(help_text='Full URL as seen in the message', max_length=2000)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed'), ('expired', 'Expired'), ('invalid', 'Invalid')], default='pending', max_length=20)),
                ('resolution_error', models.TextField(blank=True)),
                ('channel', models.ForeignKey(help_text='Channel where the invite link was posted (denormalized for fast queries)', on_delete=django.db.models.deletion.CASCADE, related_name='tg_link_events', to='audit.telegramchannel')),
                ('entity', models.ForeignKey(help_text='The URL entity in the message where this invite link was found', on_delete=django.db.models.deletion.CASCADE, related_name='tg_link_events', to='audit.messageentity')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Account used to resolve the invite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tg_link_events', to='accounts.telegramaccount')),
                ('source_link', models.ForeignKey(blank=True, help_text='Resolved destination (set once resolved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='audit.tglink')),
            ],
            options={
                'verbose_name': 'TG Link Event',
                'verbose_name_plural': 'TG Link Events',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tglink',
            index=models.Index(fields=['status'], name='audit_tglin_status_1da3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='tglink',
            index=models.Index(fields=['channel'], name='audit_tglin_channel_ad4bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='tglink',
            index=models.Index(fields=['telegram_id', 'status'], name='audit_tglin_telegra_3905f9_idx'),
        ),
        migrations.AddIndex(
            model_name='tglinkevent',
            index=models.Index(fields=['source_link'], name='audit_tglin_source__defff9_idx'),
        ),
        migrations.AddIndex(
            model_name='tglinkevent',
            index=models.Index(fields=['channel'], name='audit_tglin_channel_b6d9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tglinkevent',
            index=models.Index(fields=['resolution_status'], name='audit_tglin_resolut_d1fd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='tglinkevent',
            index=models.Index(fields=['invite_hash', 'resolution_status'], name='audit_tglin_invite__400d41_idx'),
        ),
        migrations.AddConstraint(
            model_name='tglinkevent',
            constraint=models.UniqueConstraint(fields=('entity', 'invite_hash'), name='unique_entity_invite_hash'),
        ),
    ]
