# Generated by Django 6.0.1 on 2026-04-27 04:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0050_remove_messageentity_audit_messa_entity__1fb23c_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCIBFlag",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cluster_kind",
                    models.CharField(
                        choices=[
                            ("text", "Identical text"),
                            ("media", "Identical media"),
                            ("entity", "Shared URL/entity"),
                            ("crossposter", "Speed crossposter"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "cluster_fingerprint",
                    models.CharField(db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed CIB"),
                            ("dismissed", "False positive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical CIB Flag",
                "verbose_name_plural": "historical CIB Flags",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CIBFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cluster_kind",
                    models.CharField(
                        choices=[
                            ("text", "Identical text"),
                            ("media", "Identical media"),
                            ("entity", "Shared URL/entity"),
                            ("crossposter", "Speed crossposter"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "cluster_fingerprint",
                    models.CharField(db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed CIB"),
                            ("dismissed", "False positive"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cib_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CIB Flag",
                "verbose_name_plural": "CIB Flags",
                "indexes": [
                    models.Index(
                        fields=["cluster_kind", "cluster_fingerprint"],
                        name="audit_cibfl_cluster_869aeb_idx",
                    ),
                    models.Index(
                        fields=["status"], name="audit_cibfl_status_ed1922_idx"
                    ),
                ],
                "unique_together": {("cluster_kind", "cluster_fingerprint")},
            },
        ),
    ]
