# Generated by Django 6.0.1 on 2026-01-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_archivedmessage_media_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='archivedmessage',
            new_name='downloads_a_channel_833a52_idx',
            old_name='downloads_a_channel_b8d2a4_idx',
        ),
        migrations.RenameIndex(
            model_name='archivedmessage',
            new_name='downloads_a_channel_80414e_idx',
            old_name='downloads_a_channel_c47f12_idx',
        ),
    ]
