# Generated by Django 6.0.1 on 2026-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_rename_downloads_a_channel_b8d2a4_idx_downloads_a_channel_833a52_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadtask',
            name='pending_reason',
            field=models.CharField(blank=True, choices=[('', 'Ready'), ('channel_paused', 'Channel Paused'), ('account_flood_wait', 'Account Flood Wait'), ('rate_limited', 'Rate Limited'), ('no_slots', 'No Available Slots')], default='', help_text='Why this task is pending (if applicable)', max_length=30),
        ),
    ]
