# Generated by Django 6.0.1 on 2026-01-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0005_alter_downloadtask_pending_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='media_unavailable',
            field=models.BooleanField(default=False, help_text='Media no longer available (deleted or edited)'),
        ),
        migrations.AlterField(
            model_name='downloadtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused'), ('unavailable', 'Unavailable')], db_index=True, default='pending', max_length=20),
        ),
    ]
