# Generated by Django 6.0.1 on 2026-01-11 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_telegramaccount_listener_mode'),
        ('audit', '0013_add_activity_log'),
        ('downloads', '0007_expanded_data_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('scan_history', 'Scan History'), ('scan_members', 'Scan Members'), ('check_availability', 'Check Availability')], db_index=True, max_length=50)),
                ('task_id', models.CharField(help_text='Dramatiq message ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('should_cancel', models.BooleanField(db_index=True, default=False, help_text='Flag to signal task should stop')),
                ('progress', models.JSONField(blank=True, default=dict, help_text='Task-specific progress data (e.g., messages_scanned, total_messages)')),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, help_text='Associated account (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='accounts.telegramaccount')),
                ('channel', models.ForeignKey(blank=True, help_text='Associated channel (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='audit.telegramchannel')),
            ],
            options={
                'verbose_name': 'Task Run',
                'verbose_name_plural': 'Task Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_type', 'status'], name='downloads_t_task_ty_e629d6_idx'), models.Index(fields=['channel', 'task_type', 'status'], name='downloads_t_channel_f52d23_idx')],
            },
        ),
    ]
