# Generated by Django 6.0.1 on 2026-01-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0011_fix_deleted_from_disk_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('scan_history', 'Scan History'), ('scan_members', 'Scan Members'), ('check_availability', 'Check Availability'), ('sync_channels', 'Sync Channels'), ('refresh_stats', 'Refresh Stats')], db_index=True, max_length=50),
        ),
    ]
