# Generated by Django 6.0.1 on 2026-01-13 13:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0015_historicalchannelconfig_historicaltelegramchannel'),
        ('downloads', '0012_alter_taskrun_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalArchivedMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('text', models.TextField(blank=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Message is pinned in channel')),
                ('is_post', models.BooleanField(default=False, help_text='Channel post (vs group message)')),
                ('noforwards', models.BooleanField(default=False, help_text='Message cannot be forwarded')),
                ('is_silent', models.BooleanField(default=False, help_text='Silent/no notification message')),
                ('grouped_id', models.BigIntegerField(blank=True, db_index=True, help_text='Groups media belonging to same album', null=True)),
                ('post_author', models.CharField(blank=True, help_text='Author signature on channel posts', max_length=255)),
                ('ttl_period', models.IntegerField(blank=True, help_text='Time-to-live in seconds (disappearing message)', null=True)),
                ('has_media', models.BooleanField(default=False)),
                ('media_type', models.CharField(blank=True, choices=[('photo', 'Photo'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('telegram_file_id', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('media_unavailable', models.BooleanField(default=False, help_text='Media no longer available (deleted or edited)')),
                ('sender_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('sender_username', models.CharField(blank=True, max_length=255)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('forwards', models.IntegerField(default=0)),
                ('reactions', models.JSONField(blank=True, default=dict)),
                ('telegram_date', models.DateTimeField()),
                ('edited_date', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('downloaded_file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='downloads.downloadedfile')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Archived Message',
                'verbose_name_plural': 'historical Archived Messages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDownloadedFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('file', 'File')], max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('sha256_hash', models.CharField(db_index=True, max_length=64)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('telegram_date', models.DateTimeField()),
                ('downloaded_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_from_disk', models.BooleanField(db_default=False, default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('channel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.telegramchannel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('original_file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='downloads.downloadedfile')),
                ('task', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='downloads.downloadtask')),
            ],
            options={
                'verbose_name': 'historical Downloaded File',
                'verbose_name_plural': 'historical Downloaded Files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
