# Generated by Django 6.0.1 on 2026-01-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0013_historicalarchivedmessage_historicaldownloadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('scan_history', 'Scan History'), ('scan_members', 'Scan Members'), ('fetch_profiles', 'Fetch User Profiles'), ('check_availability', 'Check Availability'), ('sync_channels', 'Sync Channels'), ('refresh_stats', 'Refresh Stats')], db_index=True, max_length=50),
        ),
    ]
