# Generated by Django 6.0.1 on 2026-01-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0022_exclusionrule_exclusion_listener_lookup_idx'),
        ('downloads', '0016_archivedmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='archivedmessage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='dedup_hash',
            field=models.CharField(blank=True, db_index=True, help_text='xxhash64 for deduplication across accounts', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='dedup_hash',
            field=models.CharField(blank=True, db_index=True, help_text='xxhash64 for deduplication across accounts', max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='archivedmessage',
            index=models.Index(fields=['channel', 'message_id'], name='downloads_a_channel_d98138_idx'),
        ),
    ]
