# Generated by Django 6.0.1 on 2026-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0024_archivedmessage_downloads_a_telegra_b1721e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='file_unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable unique file ID from Telegram - used for shared media detection', max_length=255),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='file_unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable unique file ID from Telegram - used for global deduplication', max_length=255),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='file_unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable unique file ID from Telegram (same across all bots/accounts)', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='file_unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable unique file ID from Telegram - used for shared media detection', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldownloadedfile',
            name='file_unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable unique file ID from Telegram - used for global deduplication', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaldownloadtask',
            name='file_unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stable unique file ID from Telegram (same across all bots/accounts)', max_length=255),
        ),
    ]
