# Generated by Django 6.0.2 on 2026-03-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0036_add_perf_indexes_entity_forward'),
        ('downloads', '0027_add_channel_telegram_date_idx'),
        ('events', '0002_alter_rawevents_event_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archivedmessage',
            index=models.Index(fields=['-archived_at'], name='downloads_a_archive_34b148_idx'),
        ),
    ]
