# Generated by Django 6.0.2 on 2026-03-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0028_add_archived_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='task_type',
            field=models.CharField(choices=[('scan_history', 'Scan History'), ('scan_members', 'Scan Members'), ('fetch_profiles', 'Fetch User Profiles'), ('check_availability', 'Check Availability'), ('sync_channels', 'Sync Channels'), ('sync_topics', 'Sync Forum Topics'), ('refresh_stats', 'Refresh Stats'), ('fetch_media_counts', 'Fetch Media Counts'), ('onboarding', 'Channel Onboarding'), ('download_queue', 'Download Queue'), ('media_counts', 'Media Counts'), ('stuck_recovery', 'Stuck Recovery'), ('availability_check_all', 'Availability Check (All)'), ('delete_user_media', 'Delete User Media')], db_index=True, max_length=50),
        ),
    ]
