# Generated by Django 6.0.1 on 2026-03-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0044_add_user_active_index_usergroupmembership'),
        ('downloads', '0029_alter_taskrun_task_type'),
        ('events', '0002_alter_rawevents_event_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archivedmessage',
            index=models.Index(fields=['channel', '-archived_at'], name='downloads_a_channel_b85074_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadedfile',
            index=models.Index(fields=['channel', '-downloaded_at'], name='downloads_d_channel_9d720b_idx'),
        ),
    ]
