# Generated by Django 6.0.2 on 2026-03-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0030_archivedmessage_downloads_a_channel_b85074_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='media_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds (videos/audio)', null=True),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='media_height',
            field=models.IntegerField(blank=True, help_text='Height in pixels (photos/videos)', null=True),
        ),
        migrations.AddField(
            model_name='archivedmessage',
            name='media_width',
            field=models.IntegerField(blank=True, help_text='Width in pixels (photos/videos)', null=True),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='media_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds (videos/audio)', null=True),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='media_height',
            field=models.IntegerField(blank=True, help_text='Height in pixels (photos/videos)', null=True),
        ),
        migrations.AddField(
            model_name='downloadedfile',
            name='media_width',
            field=models.IntegerField(blank=True, help_text='Width in pixels (photos/videos)', null=True),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='media_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds (videos/audio)', null=True),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='media_height',
            field=models.IntegerField(blank=True, help_text='Height in pixels (photos/videos)', null=True),
        ),
        migrations.AddField(
            model_name='historicalarchivedmessage',
            name='media_width',
            field=models.IntegerField(blank=True, help_text='Width in pixels (photos/videos)', null=True),
        ),
        migrations.AddField(
            model_name='historicaldownloadedfile',
            name='media_duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds (videos/audio)', null=True),
        ),
        migrations.AddField(
            model_name='historicaldownloadedfile',
            name='media_height',
            field=models.IntegerField(blank=True, help_text='Height in pixels (photos/videos)', null=True),
        ),
        migrations.AddField(
            model_name='historicaldownloadedfile',
            name='media_width',
            field=models.IntegerField(blank=True, help_text='Width in pixels (photos/videos)', null=True),
        ),
    ]
