# Generated by Django 6.0.2 on 2026-04-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0050_remove_messageentity_audit_messa_entity__1fb23c_idx_and_more'),
        ('downloads', '0032_alter_taskrun_task_id'),
        ('events', '0002_alter_rawevents_event_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archivedmessage',
            index=models.Index(fields=['sender_id', 'telegram_date'], name='downloads_a_sender__466bf0_idx'),
        ),
    ]
