# Generated by Django 6.0.1 on 2026-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0033_archivedmessage_downloads_a_sender__466bf0_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the message was observed as deleted (set on the deletion event)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalarchivedmessage",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the message was observed as deleted (set on the deletion event)",
                null=True,
            ),
        ),
    ]
