# Generated by Django 6.0.1 on 2026-04-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0034_archivedmessage_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="xxhash64 of normalized text - for cross-channel CIB clustering",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalarchivedmessage",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="xxhash64 of normalized text - for cross-channel CIB clustering",
                max_length=32,
                null=True,
            ),
        ),
    ]
