# Generated by Django 6.0.1 on 2026-01-19 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_globalsettings_store_raw_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEvents',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique trawlr event identifier', primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('new_message', 'New Message'), ('message_edited', 'Message Edited'), ('message_deleted', 'Message Deleted'), ('chat_action', 'Chat Action'), ('user_update', 'User Update')], db_index=True, max_length=50)),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='Telegram chat/channel ID')),
                ('message_id', models.BigIntegerField(blank=True, db_index=True, help_text='Telegram message ID (null for some event types)', null=True)),
                ('raw_json', models.JSONField(help_text='Complete raw event payload as received')),
                ('event_timestamp', models.DateTimeField(db_index=True, help_text='Timestamp of the event itself (from Telegram)')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When we received/stored this event')),
                ('account', models.ForeignKey(help_text='Account that received this event', on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='accounts.telegramaccount')),
            ],
            options={
                'verbose_name': 'Raw Event',
                'verbose_name_plural': 'Raw Events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['account', 'chat_id', 'message_id'], name='events_rawe_account_664268_idx'), models.Index(fields=['event_type', '-event_timestamp'], name='events_rawe_event_t_326ada_idx'), models.Index(fields=['-received_at'], name='events_rawe_receive_de3e2d_idx')],
            },
        ),
    ]
