# Generated by Django 6.0.1 on 2026-01-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawevents',
            name='event_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('message_edited', 'Message Edited'), ('message_deleted', 'Message Deleted'), ('chat_action', 'Chat Action'), ('user_update', 'User Update'), ('channel_update', 'Channel Update'), ('channel_participants', 'Channel Participants'), ('channel_participant', 'Channel Participant Change'), ('channel_pinned', 'Channel Pinned Message')], db_index=True, max_length=50),
        ),
    ]
